export const CATEGORIES_CREATE_REQUEST = 'CATEGORIES_CREATE_REQUEST';
export const CATEGORIES_CREATE_SUCCESS = 'CATEGORIES_CREATE_SUCCESS';
export const CATEGORIES_CREATE_FAIL = 'CATEGORIES_CREATE_FAIL';

export const CATEGORIES_RETRIEVE_REQUEST = 'CATEGORIES_RETRIEVE_REQUEST';
export const CATEGORIES_RETRIEVE_SUCCESS = 'CATEGORIES_RETRIEVE_SUCCESS';
export const CATEGORIES_RETRIEVE_FAIL = 'CATEGORIES_RETRIEVE_FAIL';

export const CATEGORIES_UPDATE_REQUEST = 'CATEGORIES_UPDATE_REQUEST';
export const CATEGORIES_UPDATE_SUCCESS = 'CATEGORIES_UPDATE_SUCCESS';
export const CATEGORIES_UPDATE_FAIL = 'CATEGORIES_UPDATE_FAIL';

export const CATEGORIES_DELETE_REQUEST = 'CATEGORIES_DELETE_REQUEST';
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS';
export const CATEGORIES_DELETE_FAIL = 'CATEGORIES_DELETE_FAIL';
