spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: secret
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

