export const PRODUCTS_CREATE_REQUEST = 'PRODUCTS_CREATE_REQUEST';
export const PRODUCTS_CREATE_SUCCESS = 'PRODUCTS_CREATE_SUCCESS';
export const PRODUCTS_CREATE_FAIL = 'PRODUCTS_CREATE_FAIL';

export const PRODUCTS_RETRIEVE_REQUEST = 'PRODUCTS_RETRIEVE_REQUEST';
export const PRODUCTS_RETRIEVE_SUCCESS = 'PRODUCTS_RETRIEVE_SUCCESS';
export const PRODUCTS_RETRIEVE_FAIL = 'PRODUCTS_RETRIEVE_FAIL';

export const PRODUCTS_UPDATE_REQUEST = 'PRODUCTS_UPDATE_REQUEST';
export const PRODUCTS_UPDATE_SUCCESS = 'PRODUCTS_UPDATE_SUCCESS';
export const PRODUCTS_UPDATE_FAIL = 'PRODUCTS_UPDATE_FAIL';

export const PRODUCTS_DELETE_REQUEST = 'PRODUCTS_DELETE_REQUEST';
export const PRODUCTS_DELETE_SUCCESS = 'PRODUCTS_DELETE_SUCCESS';
export const PRODUCTS_DELETE_FAIL = 'PRODUCTS_DELETE_FAIL';
